### PR TITLE
:package: swagger-ui-dist to latest version

### PR DESCRIPTION
**Pull request by BePo65**
Solves issue #185.

Unable to run tests on my machine (windows 10; node 14.4.0).

### CODE REVIEW

**Comment by yinzara** [comment]
3.27 is out and this PR isn't yet merged. Can we get it changed to 3.27?

3.27 includes https://github.com/swagger-api/swagger-ui/pull/6037

**Comment by BePo65** [comment]
swagger-ui version 3.27 runs also fine.

**Comment by BePo65** [comment]
how about also switching from phantomjs to puppeteer as phantomjs is deprecated for more than 2 years (see [phantomjs on github)](https://github.com/ariya/phantomjs/issues/15344)?
PR #196 would solve this issue.

**Comment by yinzara** [comment]
@scottie1984 Any chance we could get a release with this?

**Comment by tan-dd** [comment]
Why is not this PR getting merged? 3.35 is out as well

**Comment by tanmoy-git** [comment]
I have published this package with the updated swagger-ui-dist version. You may use it alternatively to enjoy the latest offerings by Open API 3 : https://www.npmjs.com/package/swagger-ui-express-updated
```
npm i swagger-ui-express-updated
```

**Comment by kevinccbsg** [comment]
Hi @scottie1984 Any chance we could get a release with this?

**Comment by mentatxx** [comment]
This patch is not really needed - you can just upgrade packages.
By fresh install i'm getting 3.45.0 with original ^3.18.1 version specifier
```
{
  "_from": "swagger-ui-dist@^3.18.1",
  "_id": "swagger-ui-dist@3.45.0",
```

**Comment by BePo65** [comment]
You are right (of course :-). I deleted my 'node_modules' folder and the 'package-lock.json' file and then reinstalled the packages with `npm i` and voila the 'swagger-ui-dist' was updated to V3.45.1.

So I close this pr as being unnecessary.

**Pull request closed without merging**
