### PR TITLE
Update to version 5

### PR DESCRIPTION
**Pull request by scottie1984**

### CODE REVIEW

**Comment by zuozp8** [comment]
I copied `index.js` from this branch to my `node_modules/swagger-ui-express/` and it fixed the issue and everything seems to work fine

**Comment by Tornquist** [comment]
@scottie1984 Is there a plan to release this?

I reviewed the conflicts and they're minor. I'm happy to fork this and put up another PR that's your preferred workflow.

**Comment by scottie1984** [comment]
> @scottie1984 Is there a plan to release this?
> 
> I reviewed the conflicts and they're minor. I'm happy to fork this and put up another PR that's your preferred workflow.

No- I reverted the issue with the shared variable in master instead of this fix.

To run multiple swagger ui instances I am going to document the serveFiles function

**Comment by Tornquist** [comment]
Great, thanks for the quick response.

**Comment by scottie1984** [comment]
@rickihastings  - yes this fix doesn't work. However for https://github.com/scottie1984/swagger-ui-express/issues/183 there seems to be a proxy fix that is not related to this module.

**Pull request closed without merging**
